# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qvfsmodDialog
                                 A QGIS plugin
 This plugin allows the use of Vfsmod in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-09
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Iñigo Barberena
        email                : inigo.barberena@unavarra.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from PyQt5 import uic
from PyQt5 import QtWidgets

# Cargar el archivo .ui para una Main Window
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Qvfsmod_dialog_base.ui'))

class qvfsmodMainWindow(QtWidgets.QMainWindow, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(qvfsmodMainWindow, self).__init__(parent)
        # Configurar la interfaz de usuario a través de FORM_CLASS
        self.setupUi(self)